---
version: '3.2'

services:
  build_deployment_package:
    build: .
    image: "cisagov/example_lambda"
    entrypoint: ./build/build_artifact.sh
    volumes:
      - .:/var/task/output
  run_lambda_locally:
    build: .
    image: "cisagov/example_lambda"
    ports:
      - "9000:8080"
